# Do not edit. Generated by the configure script.
{
  "variables": {
    "host_arch": "mac", 
    "stud_debug": "false", 
    "target_arch": "mac", 
    "stud_prefix": ""
  }, 
  "target_defaults": {
    "libraries": [], 
    "defines": [], 
    "cflags": [], 
    "include_dirs": []
  }
}
